import { data } from "react-router";
import { IMAGES } from "./images";

// why choose us cards
export const MAIN_SEARCH_BAR_DATA = {
  items: [
    {
      title: "Buy",
      filterOptions: {
        checkOptions: ["Full House", "Land/Plot"],
        dropDownOptions: [
          {
            name: "BHK Type",
            type: "select",
            Options: ["1 RK", "1 BHK", "2 BHK", "3 BHK", "4 BHK", "4+ BHK"],
          },
          {
            name: "Property Status",
            type: "dropdown",
            Options: ["Under Construction", "Ready"],
          },
        ],
      },
    },
    {
      title: "Rent",
      filterOptions: {
        checkOptions: ["Full House", "PG/Hostel", "Flatmates"],
        dropDownOptions: [
          {
            name: "BHK Type",
            type: "select",
            Options: ["1 RK", "1 BHK", "2 BHK", "3 BHK", "4 BHK", "4+ BHK"],
          },
          {
            name: "Availability",
            type: "dropdown",
            Options: [
              "Immediate",
              "Within 15 days",
              "Within 30 days",
              "After 30 days",
            ],
          },
        ],
      },
    },
    {
      title: "Commercial",
      filterOptions: {
        checkOptions: ["Buy", "Rent"],
        dropDownOptions: [
          {
            name: "BHK Type",
            type: "select",
            Options: ["1 RK", "1 BHK", "2 BHK", "3 BHK", "4 BHK", "4+ BHK"],
          },
        ],
      },
    },
  ],
};

export const WHY_CHOOSE_US_CARDS = {
  heading: "Why Choose Us?",
  cards: [
    {
      icon: IMAGES.COURSE_ICON_1,
      title: "Comprehensive Listings",
      content: "Explore various properties with insights, images, and prices.",
    },
    {
      icon: IMAGES.COURSE_ICON_2,
      title: "Expert Guidance",
      content: "Our experienced real estate agents assist you at every step.",
    },
    {
      icon: IMAGES.COURSE_ICON_3,
      title: "User-Friendly Experience",
      content: "Seamlessly search, filter, and connect with sellers or buyers.",
    },
    {
      icon: IMAGES.COURSE_ICON_4,
      title: "Secure & Transparent",
      content: "Reliable property management with clear documentation.",
    },
  ],
};

// our services

export const OUR_SERVICES = {
  heading: "Our Services",
  cards: [
    {
      img: IMAGES.SERVICES_IMG_1,
      title: "Rent & Lease",
    },
    {
      img: IMAGES.SERVICES_IMG_2,
      title: "Buy & Sell",
    },
    {
      img: IMAGES.SERVICES_IMG_3,
      title: "Property Management",
    },
  ],
};

// how it works

export const HOW_IT_WORKS_CARDS = {
  heading: "How it works",
  cards: [
    {
      icon: IMAGES.HOW_IT_WORKS_1,
      title: "Sign Up & Choose Your Role",
      content: "Register as a Buyer, Seller, or Real Estate Agent.",
    },
    {
      icon: IMAGES.HOW_IT_WORKS_2,
      title: "Explore & List Properties",
      content: "Browse listings or add your property for sale or rent.",
    },
    {
      icon: IMAGES.HOW_IT_WORKS_3,
      title: "Connect & Finalize Deals",
      content:
        "Direct communication between buyers and sellers for smooth transactions.",
    },
    {
      icon: IMAGES.HOW_IT_WORKS_4,
      title: "Manage Your Dashboard",
      content:
        "Keep track of saved properties, inquiries, and deals in one place.",
    },
  ],
};

export const BOTTOM_CONTENT = {
  title: `Get Started Today!`,
  content: `Join thousands of satisfied users and find the perfect property with us. 
Sign up now and start exploring!`,
  btnText: "Post Free Property Ad",
};

export const LOCATION_DATA = [
  "Charminar",
  "Golconda Fort",
  "Hussain Sagar Lake",
  "Ramoji Film City",
  "Salar Jung Museum",
  "Birla Mandir",
  "Necklace Road",
  "Lumbini Park",
  "Chilkur Balaji Temple",
  "Qutb Shahi Tombs",
  "Shilparamam",
  "Snow World",
  "KBR National Park",
  "Jubilee Hills",
  "Banjara Hills",
  "HiTech City",
  "Cyber Towers",
  "Durgam Cheruvu",
  "Inorbit Mall",
  "Forum Sujana Mall",
  "GVK One Mall",
  "Tank Bund",
  "Mecca Masjid",
  "Laad Bazaar",
  "Nehru Zoological Park",
  "Botanical Gardens",
  "Public Gardens",
  "Osmania University",
  "Moula Ali Dargah",
  "Taramati Baradari",
  "Sudha Cars Museum",
  "Mount Opera",
  "Peddamma Temple",
  "Shamirpet Lake",
  "Mrugavani National Park",
  "Mahavir Harina Vanasthali",
  "Chowmahalla Palace",
  "Paigah Tombs",
  "Begumpet",
  "Ameerpet",
  "Secunderabad",
  "Koti",
  "Madhapur",
  "Kondapur",
  "Gachibowli",
  "RTC Cross Roads",
  "Somajiguda",
  "LB Nagar",
  "Uppal",
];
export const FILTER_DATA = [
  {
    id: "bhkType",
    label: "BHK Type",
    type: "checkbox",
    options: [
      { id: "1-rk", value: "1 RK" },
      { id: "1-bhk", value: "1 BHK" },
      { id: "2-bhk", value: "2 BHK" },
      { id: "3-bhk", value: "3 BHK" },
      { id: "4-bhk", value: "4 BHK" },
      { id: "4+-bhk", value: "4+ BHK" },
    ],
  },
  {
    id: "range",
    label: "Rent Range",
    type: "range",
    min: 0,
    max: 80000000,
    step: 1000,
  },
  {
    id: "availability",
    label: "Availability",
    type: "radio",
    options: [
      { id: "0", value: "Immediate" },
      { id: "<15", value: "Within 15 Days" },
      { id: "<30", value: "Within 30 Days" },
      { id: ">30", value: "After 30 Days" },
    ],
  },
  {
    id: "preferredTenants",
    label: "Preferred Tenants",
    type: "checkbox",
    options: [
      { id: "family", value: "Family" },
      { id: "company", value: "Company" },
      { id: "bachelor-male", value: "Bachelor Male" },
      { id: "bachelor-female", value: "Bachelor Female" },
    ],
  },
  {
    id: "preferredType",
    label: "Preferred Type",
    type: "checkbox",
    options: [
      { id: "apartement", value: "Apartment" },
      { id: "independent-house/villa", value: "Independent House/Villa" },
      { id: "gated-community-villa", value: "Gated Community villa" },
    ],
  },
  {
    id: "furnishing",
    label: "Furnishing",
    type: "checkbox",
    options: [
      { id: "full", value: "Full" },
      { id: "semi", value: "Semi" },
      { id: "none", value: "None" },
    ],
  },
  {
    id: "parking",
    label: "Parking",
    type: "checkbox",
    options: [
      { id: "2", value: "2 Wheeler" },
      { id: "4", value: "4 Wheeler" },
    ],
  },
];

export const PRODUCT_ADD_DATA = [
  {
    id: "propertyDetails",
    name: "Property Details",
    icon: IMAGES.PROPERTY_DETAILS_ICON,
    inputFeilds: [
      {
        type: "dropdown",
        id: "apartmentType",
        label: "Apartment Type",
        required: true,
        options: [
          "Select",
          "Apartment",
          "Independent House/Villa",
          "Gated Community Villa",
        ],
      },
      {
        type: "dropdown",
        id: "bhkType",
        label: "BHK Type",
        required: true,
        options: [
          "Select",
          "1 RK",
          "1 BHK",
          "2 BHK",
          "3 BHK",
          "4 BHK",
          "4+ BHK",
        ],
      },
      {
        type: "dropdown",
        id: "floor",
        label: "Floor",
        required: true,
        options: [
          "Select",
          "Ground",
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "58",
          "59",
          "60",
          "61",
          "62",
          "63",
          "64",
          "65",
          "66",
          "67",
          "68",
          "69",
          "70",
          "71",
          "72",
          "73",
          "74",
          "75",
          "76",
          "77",
          "78",
          "79",
          "80",
          "81",
          "82",
          "83",
          "84",
          "85",
          "86",
          "87",
          "88",
          "89",
          "90",
          "91",
          "92",
          "93",
          "94",
          "95",
          "96",
          "97",
          "98",
          "99",
        ],
      },
      {
        type: "dropdown",
        id: "totalFloor",
        label: "Total Floor",
        required: true,
        options: [
          "Select",
          "Ground",
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "58",
          "59",
          "60",
          "61",
          "62",
          "63",
          "64",
          "65",
          "66",
          "67",
          "68",
          "69",
          "70",
          "71",
          "72",
          "73",
          "74",
          "75",
          "76",
          "77",
          "78",
          "79",
          "80",
          "81",
          "82",
          "83",
          "84",
          "85",
          "86",
          "87",
          "88",
          "89",
          "90",
          "91",
          "92",
          "93",
          "94",
          "95",
          "96",
          "97",
          "98",
          "99",
        ],
      },
      {
        type: "dropdown",
        id: "propertyAge",
        label: "Property Age",
        required: true,
        options: [
          "Select",
          "Less than a year",
          "1 to 3 year",
          "3 to 5 year",
          "5 to 10 year",
          "More than 10 year",
        ],
      },
      {
        type: "dropdown",
        id: "facing",
        label: "Facing",
        required: false,
        options: [
          "Select",
          "North",
          "South",
          "East",
          "West",
          "North-East",
          "South-East",
          "North-West",
          "South-West",
          "Don't Know",
        ],
      },
      {
        type: "input",
        id: "builtUpArea",
        label: "Built Up Area",
        required: true,
        subText: "Sq.ft",
        placeHolder: "Built Up Area",
      },
    ],
  },
  {
    id: "localityDetails",
    name: "Locality Details",
    icon: IMAGES.LOCALITY_DETAILS_ICON,
    inputFeilds: [
      {
        type: "dropdown",
        id: "city",
        label: "City",
        required: true,
        options: [
          "Select",
          "Bangalore",
          "Mumbai",
          "Pune",
          "Chennai",
          "Gurgaon",
          "Hyderabad",
          "Delhi",
          "Faridabad",
          "Ghaziabad",
          "Noida",
          "Greater Noida",
        ],
      },
      {
        type: "input",
        id: "landmark",
        label: "Landmark / Street",
        placeHolder: "Eg. Evergreen Street",
        required: true,
      },
      {
        type: "getLocation",
        id: "locality",
        label: "Locality",
        required: true,
        locationIcon: IMAGES.LOCATION_ICON,
        GpsIcon: IMAGES.GPS_ICON,
        GpsLabel: "Use current location",
        placeHolder: "Enter Location",
      },
    ],
  },
  {
    id: "rentalDetails",
    name: "Rental Details",
    icon: IMAGES.RENTAL_DETAILS_ICON,
    inputFeilds: [
      {
        type: "radio",
        id: "propertyAvailableFor",
        label: "Property available for",
        required: true,
        options: ["Sell","Rent", "Lease","Manage"],
      },
      {
        type: "radio",
        id: "propertytype",
        label: "Property Type",
        required: true,
        options: ["Commercial","Non-Commercial"],
      },
      {
        type: "input",
        id: "expectedRent",
        label: "Expected Rent",
        required: true,
        preText: "₹",
        subText: "/Month",
        placeHolder: "Enter Amount",
      },
      {
        type: "input",
        id: "expectedDeposit",
        label: "Expected Deposit",
        required: true,
        preText: "₹",
        subText: "/Month",
        placeHolder: "Enter Amount",
      },
      {
        type: "input",
        id: "maintenanceAmount",
        label: "Maintenance Amount",
        required: true,
        preText: "₹",
        subText: "/Month",
        placeHolder: "Enter Amount",
      },
      {
        type: "date",
        id: "availableFrom",
        label: "Available From",
        required: true,
      },

      {
        type: "dropdown",
        id: "furnishing",
        label: "Furnishing",
        required: true,
        options: ["Select", "Fully furnished", "Semi-furnished", "Unfurnished"],
      },
      {
        type: "dropdown",
        id: "parking",
        label: "Parking",
        required: true,
        options: ["Select", "Bike", "Car", "Both", "None"],
      },
      {
        type: "checkbox",
        id: "preferredTenants",
        label: "Preferred Tenants",
        required: true,
        options: [
          "Anyone",
          "Family",
          "Bachelor Female",
          "Bachelor Male",
          "Company",
        ],
      },
      {
        type: "text-box",
        id: "rentalDescription",
        label: "Description",
        required: false,
        placeHolder:
          "Write a few lines about your property something which is special and makes your property stand out. Please do not mention your contact details in any format.",
      },
    ],
  },
  {
    id: "amenities",
    name: "Amenities",
    icon: IMAGES.RENTAL_DETAILS_ICON,
    inputFeilds: [
      {
        type: "number",
        id: "bathroom",
        label: "Bathroom(s)",
        required: true,
        plusIcon: IMAGES.PLUS_ICON,
        minusIcon: IMAGES.MINUS_ICON,
      },
      {
        type: "number",
        id: "balcony",
        label: "Balcony",
        required: false,
        plusIcon: IMAGES.PLUS_ICON,
        minusIcon: IMAGES.MINUS_ICON,
      },
      {
        type: "dropdown",
        id: "waterSupply",
        label: "Water Supply",
        required: false,
        options: ["Select", "Corporation", "Bore Well", "Both"],
      },
      {
        type: "radio",
        id: "gym",
        label: "GYM",
        required: true,
        options: ["Yes", "No"],
      },
      {
        type: "radio",
        id: "nonVeg",
        label: "Non-Veg Allowed",
        required: true,
        options: ["Yes", "No"],
      },
      {
        type: "radio",
        id: "gatedSecurity",
        label: "Gated Security",
        required: true,
        options: ["Yes", "No"],
      },
      {
        type: "dropdown",
        id: "showingProperty",
        label: "Who will show the property?",
        required: true,
        options: [
          "Select",
          "I will show",
          "Neighbours",
          "Friends/Relatives",
          "Security",
          "Tenants",
          "Others",
        ],
      },
      {
        type: "dropdown",
        id: "propertyCondition",
        label: "Current Property Condition?",
        required: true,
        options: [
          "Select",
          "Vacant",
          "Tenant on Notice Period",
          "New Property",
          "Need Help to Manage",
        ],
      },
      {
        type: "input",
        id: "secondaryNumber",
        label: "Secondary Number",
        required: true,
        placeHolder: "Secondary Number",
      },
      {
        type: "text-box",
        id: "amenitiesDescription",
        label: "Add Directions Tip for your tenants",
        required: false,
        placeHolder:
          "Eg. Take the road opposite to Amrita College, take right after 300m...",
      },
      {
        type: "checkbox",
        id: "avalableAminities",
        label: "Select the available amenities",
        required: false,
        options: [
          "Lift",
          "Air Conditioner",
          "Intercom",
          "Children Play Area",
          "Servant Room",
          "Gas Pipeline",
          "Rain Water Harvesting",
          "House Keeping",
          "Visitor Parking",
          "Internet Services",
          "Club House",
          "Swimming Pool",
          "Fire Safety",
          "Shopping Center",
          "Park",
          "Sewage Treatment Plant",
          "Power Backup",
        ],
      },
    ],
  },
  {
    id: "gallery",
    name: "Gallery",
    icon: IMAGES.GALLERY_ICON,
    inputFeilds: [
      {
        type: "upload",
        id: "images",
        label: "Add photos to get 5X more responses.",
        btn: "Add Photos",
      },
    ],
  },
  {
    id: "schedule",
    name: "Schedule",
    icon: IMAGES.SCHEDULE_ICON,
    inputFeilds: [
      {
        type: "dropdown",
        id: "availability",
        label: "Availability",
        options: [
          "Select",
          "Everyday Mon-Sun",
          "Weekday Mon-Fri",
          "Weekend Sat,Sun",
        ],
      },
      {
        type: "checkbox",
        id: "schedule",
        label: "Select Time Schedule",
        options: [
          "Available All Day",
          "Available Morning",
          "Available Afternoon",
        ],
      },
    ],
  },
];

export const FOOTER_LIST = [
  {
    name: "Real Estate",
    propertyList: [
      "Flats in Mumbai",
      "Flats in Bangalore",
      "Flats in Hyderabad",
      "Flats in Pune",
      "Flats in Chennai",
      "Flats in Delhi",
      "Flats in Gurgaon",
      "Flats in Noida",
      "Flats in Kolkata",
      "Flats in Ahmedabad",
      "Flats in Thane",
      "Flats in Navi Mumbai",
      "Flats in Faridabad",
      "Flats in Ghaziabad",
      "Flats in Coimbatore",
      "Properties in India",
      "Agriculture Lands in India",
      "Plots in India",
      "Flats in India",
    ],
  },
  {
    name: "Rentals",
    propertyList: [
      "Flats for rent in Mumbai",
      "Flats for rent in Bangalore",
      "Flats for rent in Hyderabad",
      "Flats for rent in Pune",
      "Flats for rent in Chennai",
      "Flats for rent in Delhi",
      "Flats for rent in Gurgaon",
      "Flats for rent in Noida",
      "Flats for rent in Kolkata",
      "Flats for rent in Ahmedabad",
      "Flats for rent in Thane",
      "Flats for rent in Navi Mumbai",
      "Flats for rent in Faridabad",
      "Flats for rent in Ghaziabad",
      "Flats for rent in Coimbatore",
    ],
  },
  {
    name: "PG’s",
    propertyList: [
      "PG's in Mumbai",
      "PG's in Bangalore",
      "PG's in Hyderabad",
      "PG's in Pune",
      "PG's in Chennai",
      "PG's in Delhi",
      "PG's in Gurgaon",
      "PG's in Noida",
      "PG's in Kolkata",
      "PG's in Ahmedabad",
      "PG's in Thane",
      "PG's in Navi Mumbai",
      "PG's in Faridabad",
      "PG's in Ghaziabad",
      "PG's in Coimbatore",
    ],
  },
  {
    name: "Property Management",
    propertyList: [
      "Properties in India",
      "Agriculture Lands in India",
      "Plots in India",
      "Flats in India",
    ],
  },
  {
    name: "Popular",
    propertyList: [
      "Mumbai",
      "Bangalore",
      "Hyderabad",
      "Pune",
      "Chennai",
      "Delhi",
      "Gurgaon",
      "Noida",
      "Kolkata",
      "Ahmedabad",
      "Thane",
      "Navi Mumbai",
      "Faridabad",
      "Ghaziabad",
      "Coimbatore",
    ],
  },
];


export const formatToIndianNumber=(num)=> {
  if (num >= 10000000) {
    return (num / 10000000) + ' Cr';
  } else if (num >= 100000) {
    return (num / 100000) + ' Lakh';
  } else {
    return num.toString();
  }
}